server:
  port: ${vcap.application.port:8762}   # HTTP port
spring:
  application:
    name: RegisterDiscoveryService
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
   security:
     enabled : false