appbase:
    enable: false
    roles:
     - 1
     - 2
     - 3
spring:
  application:
    name: CompanyDemoService
eureka:

  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8085
#      datasource:
#          url: jdbc:mysql://localhost:3306/test
#          password:
#          driver-class-createBy: com.mysql.jdbc.Driver

