spring:
  application:
    name: AnotherService
eureka:

  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8084
#      datasource:
#          url: jdbc:mysql://localhost:3306/test
#          password:
#          driver-class-createBy: com.mysql.jdbc.Driver

